### ISSUE TITLE
Feature request: text only message

### ISSUE THREAD

**Issue by kilianc** [segmentio/integration-slack#13]
It's a little bit overwhelming to have the entire event on slack when in reality you just need a sentence with a link.

**Comment by f2prateek** [comment]
What would the message link to?

**Comment by kilianc** [comment]
@f2prateek my comment was misleading, the link is the user responsibility, I think we can do that using the message template, is that correct?

`Hey channel, new user {{email}} just signed up: http://admin.myapp.com/users/{{userid}}`

:)

**Comment by f2prateek** [comment]
Yeah I don't like the fat output in slack currently. It's hard to say what's useful or not. We might experiment with only showing the entire event (as is now) if there is no custom template. And if there is a custom template, we'll skip the properties, context, etc.

**Comment by kilianc** [comment]
That would be great! Keep me updated so that I can turn it on again!

**Comment by f2prateek** [comment]
The heavy output is gone, and only the text is shown.

**Comment by kilianc** [comment]
@f2prateek that's awesome.
