### ISSUE TITLE
format?

### ISSUE THREAD

**Issue by yields** [segmentio/integration-slack#4]
```js
slack.settings.fmt = '{{properties.name}} {{event}}'; // => "John Opened an issue"
```

Probably insecure though haha :P

**Comment by f2prateek** [comment]
haha yeah we already have this as a feature in the next version!

**Comment by f2prateek** [comment]
what's a good handlebar library for node btw?

**Comment by yields** [comment]
dunno, i mostly used tj/minstach, but those are overkill IMO.
maybe just a simple thing like https://github.com/matthewmueller/subs would be fine.
